#
# Makefile - makefile for common code
#
# Copyright (c) 2009 André Jucovsky Bianchi
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

#-----------------------------------------------------------------------------
# This makefile has rules for building common code.
#
# See the README file for instructions.
#-----------------------------------------------------------------------------

# rules for auxiliary library binaries

include ../common/common.mk

target: $(OBJ)
